### ISSUE TITLE
Remove notification modules

### ISSUE THREAD

**Issue by etj** [GeoNode/geoserver-geonode-ext#101]
Notification module is not needed at the moment, and may cause issues (see https://github.com/geosolutions-it/C183-ALMAVIVA-2020-GeoNode-DEV/issues/324).
Remove the 3 jars from the build.

This is a regression, since the modules have already been removed on 2.18.x (see commits linked to #81)

**Comment by giohappy** [comment]
This requires the rebuild of GS 2.19.6 and 2.20.4.
@randomorder maybe this can be done with #104
