### ISSUE TITLE
Create Geoserver build for 2.20.5

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geoserver-geonode-ext#119]
@randomorder as soon as 2.20.5 will be [available in June](https://github.com/geoserver/geoserver/wiki/Release-Schedule) we will have to make [the build](https://build.geo-solutions.it/jenkins/view/GeoNode/job/GeoNode-GeoServer-EXT-2.20.4/) for it.

This is needed to have the fix in https://osgeo-org.atlassian.net/browse/GEOS-10454

**Comment by randomorder** [comment]
artifacts are available:
https://artifacts.geonode.org/geoserver/2.20.5/geoserver.war
