### ISSUE TITLE
Upgrading to GeoTools 30.x series, refactor to org.geotools.api interfaces

### ISSUE THREAD

**Issue by jodygarnett** [GeoNode/geoserver-geonode-ext#173]
As part of https://github.com/geotools/geotools/wiki/Remove-OpenGIS we are contacting affected projects to coordinate upgrade to GeoTools 30.x series and refactoring the org.opengis package to org.geotools.api.

See also https://github.com/GeoNode/geoserver-geonode-ext/issues/172

**Comment by jodygarnett** [comment]
For more information see https://geotoolsnews.blogspot.com/2023/07/construction-ahead-refactoring.html

**Comment by jodygarnett** [comment]
We have had a good result from the code sprint folding in all the functionality from https://github.com/geosolutions-it/mapfish-print fork into https://github.com/mapfish/mapfish-print-v2 and having it build with Java 11 and the GeoTools API change.

The net result is that GeoNode should be usable with the out-of-the-box geoserver-2.24.x-printing-plugin.zip. Indeed if you download a [nightly build](https://geoserver.org/release/main/) you could confirm this for us.

We would like to make sure you are happy before making the GeoServer 2.24.0 release.

**Comment by giohappy** [comment]
@jodygarnett we're going to test the new mapfish print soon
