### ISSUE TITLE
docker-compose up -d brings up an error for Geonode 4.1.0

### ISSUE THREAD

**Issue by lcoandrade** [GeoNode/geoserver-geonode-ext#174]
## Expected Behavior
Install Geonode with Docker

## Actual Behavior
When executing `docker-compose up -d` I get an error:
```
ERROR: for django Container "c3f210cb7cb0" is unhealthy
ERROR: Encountered errors while bringing up the project
```

## Steps to Reproduce the Problem

  1.`cd /opt`
  2.`sudo git clone https://github.com/GeoNode/geonode.git -b 4.1.0 —depth 1`
  3. `cd geonode`
  4. `docker-compose up -d`

## Specifications

  - GeoNode version:4.1.0
  - Installation type (vanilla, geonode-project):vanilla
  - Installation method (manual, docker):docker
  - Platform:Ubuntu 22.04 on VirtualBox
  - Additional details:

**Comment by giohappy** [comment]
@afabiani we must grant backward compatibility by checking wether the new variable (`GEONODE_GEODATABASE_USER`) is set, otherwise revert to using the old one (`GEONODE_GEODATABASE`).

**Comment by giohappy** [comment]
@lcoandrade a new image has been pushed to Docker Hub with the fix. 
Now it should work also with the older env var. Could you test it?

**Comment by lcoandrade** [comment]
Ok. I'm starting from scratch with a Ubuntu 22.04 (already with Docker) in my VirtualBox.

**Comment by lcoandrade** [comment]
Same error:
<img width="731" alt="Captura de Tela 2023-08-24 às 10 00 26" src="https://github.com/GeoNode/geoserver-geonode-ext/assets/8769816/3a2bba91-96f7-4979-b917-ee8a71e6cf59">

**Comment by giohappy** [comment]
@lcoandrade can you please try again?

**Comment by lcoandrade** [comment]
Ok! I'll try again.

**Comment by lcoandrade** [comment]
Now, it's ok!!!!
Problem solved.
Thank you for the quick response!
