### ISSUE TITLE
Updating geoserver.war

### ISSUE THREAD

**Issue by jean** [GeoNode/geoserver-geonode-ext#25]
How does http://build.geonode.org/geoserver/latest/geoserver.war get updated?
How can I build a new geoserver.war for development?

**Comment by jj0hns0n** [comment]
@jean the build has been updated and is here now http://52.5.141.226/job/geoserver-geonode-dev/org.opengeo$geonode-geoserver-ext/ and the war goes to http://52.5.141.226/geoserver/latest/ .. This URL will be updated to build.geonode.org shortly.

**Comment by jean** [comment]
@jj0hns0n cool! Is this now automated such that the `.war` will stay up to date in future?

**Comment by jj0hns0n** [comment]
Yes, the DNS has been updated. This directory will now have updated wars on an ongoing basis.

http://build.geonode.org/geoserver/latest/

**Comment by jean** [comment]
awesome :-)
