### ISSUE TITLE
 relation "security_genericobjectrolemapping" does not exist

### ISSUE THREAD

**Issue by menegon** [GeoNode/geoserver-geonode-ext#29]
After a fresh installation of GeoNode 2.4 I have tried  the "Security Integration Optimization" [1] and it
works fine for authenticated user.
Unfortunately, for anonymous user it does not work due to a DB error.
"""
 ERROR:  relation "security_genericobjectrolemapping" does not exist
at character
"""

(geonode.security.models no longer contain the GenericObjectRoleMapping model)

[1] http://docs.geonode.org/en/dev/deploy/production.html#security-integration-optimization

**Comment by jj0hns0n** [comment]
The security models have completely changed. @ischneider is it possible for you to update the DB security procedures to use the new security model?

**Comment by ischneider** [comment]
@jj0hns0n This is already done, it seems: 19584f4b7344d4cf5da3b9d11103c547371d7b62

I haven't looked at it or tested but my guess is that if you're still seeing the issue, a new geoserver build is required to pull this in.

**Comment by garnertb** [comment]
@ischneider is right, the Geoserver was built 19-May-2014 05:07 and that PR was merged on 16-Dec-2014.

**Comment by jj0hns0n** [comment]
@ingenieroariel @simod how do we most easily do a new geoserver build.
