### ISSUE TITLE
Issue with "Connection information for the geogig security logs database."

### ISSUE THREAD

**Issue by pjdufour** [GeoNode/geoserver-geonode-ext#56]
An issue with "Connection information for the geogig security logs database." is preventing GeoServer from starting properly.  It looks like the url wasn't properly configured for production and still pointing to `jdbc\:sqlite\:F\:\\work...`

https://github.com/GeoNode/geoserver-geonode-ext/blob/master/src/main/webapp/data/geogig/config/security/logstore.properties#L18

--

04 Jan 22:14:15 ERROR [org.springframework.web.context.ContextLoader] - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'geogigSecurityLogStore' defined in URL [jar:file:/var/lib/tomcat8/webapps/geoserver/WEB-INF/lib/gs-geogig-2.9-SNAPSHOT.jar!/applicationContext.xml]: Invocation of init method failed; nested exception is java.lang.RuntimeException: java.sql.SQLException: opening db: 'F:\work\code\java\geonode\geoserver-geonode-ext.GeoNode\src\main\webapp\data\geogig\config\security\securitylogs.db': Permission denied
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1578)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFact

**Comment by afabiani** [comment]
Removed that file. It is automatically created by GeoGig when starting GeoServer.
