### ISSUE TITLE
Rebuild datadir for Geoserver with fixed cache configs

### ISSUE THREAD

**Issue by giohappy** [GeoNode/geoserver-geonode-ext#91]
@randomorder the datadir must be rebuilt after the latest fixes to GWC defaults https://github.com/GeoNode/geoserver-geonode-ext/commit/8ddb867ee81edfa16101d845644db42ea2f1f400

**Comment by randomorder** [comment]
done @giohappy 
https://hub.docker.com/r/geonode/geoserver_data/tags
